server:
  port: 18082

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        instance-enabled: true

#      username: nacos
#      password: nacos

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*' #必须使用单引号，不可以直接使用*
